### ISSUE TITLE
allow_mult gets stuck in `true` state

### ISSUE THREAD

**Issue by peschkaj** [basho/riak_kv#660] opened 2013-09-12 03:28 UTC
Starting with a new bucket, I have bucket properties like so:

```
{"props":{"search":false,"allow_mult":false,"basic_quorum":false,"big_vclock":50,"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"dw":"quorum","last_write_wins":false,"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"n_val":3,"name":"players","notfound_ok":true,"old_vclock":86400,"postcommit":[],"pr":0,"precommit":[],"pw":0,"r":"quorum","rw":"quorum","small_vclock":50,"w":"quorum","young_vclock":20}}
```

Setting `allow_mult = true` and `last_write_wins = false` results in the following:

```
{"props":{"allow_mult":true,"basic_quorum":false,"big_vclock":50,"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"dw":"quorum","last_write_wins":false,"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"n_val":3,"name":"players","notfound_ok":true,"old_vclock":86400,"postcommit":[],"pr":0,"precommit":[],"pw":0,"r":1,"rw":"quorum","search":false,"small_vclock":50,"w":1,"young_vclock":20}}
```

Setting `allow_mult = false` and `LWW = true` actually ends up with allow_mult = true and LWW = true:

```
{"props":{"allow_mult":true,"basic_quorum":false,"big_vclock":50,"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"dw":"quorum","last_write_wins":true,"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"n_val":3,"name":"players","notfound_ok":true,"old_vclock":86400,"postcommit":[],"pr":0,"precommit":[],"pw":0,"r":1,"rw":"quorum","search":false,"small_vclock":50,"w":1,"young_vclock":20}}
```

**Comment by peschkaj** [comment] 2013-09-12 03:28
Steps to repro with C# are in https://gist.github.com/peschkaj/6532771

**Comment by jrwest** [comment] 2014-03-24 21:59
moved to `2.0-RC` and marked for resilience testing (because I want to investigate). We changed a bunch of code around bucket property handling and it would be good to know where we stand w/ this issue.

**Comment by jrwest** [comment] 2014-04-18 04:37
Using curl against `develop` I have been unable to reproduce. I'm going to go ahead and close this out. Please re-open if this comes up again or you find results to the contrary.

Default values before any operations:

```
$ curl http://localhost:8098/buckets/bucket/props | python -mjson.tool | grep -iE "allow_mult|last_write_wins"
        "allow_mult": false,
        "last_write_wins": false,
```

Set `allow_mult=true`/`last_write_wins=false`:

```
$ curl -v -X PUT -H "content-type: application/json" -d '{"props": {"allow_mult": true, "last_write_wins": false}}' http://localhost:8098/buckets/bucket/props

$ curl -v http://localhost:8098/buckets/bucket/props | python -mjson.tool | grep -iE "allow_mult|last_write_wins"
        "allow_mult": true,
        "last_write_wins": false,
```

set `allow_mult=false`/`last_write_wins=true` on the same bucket:

```
$ curl -v -X PUT -H "content-type: application/json" -d '{"props": {"allow_mult": false, "last_write_wins": true}}' http://localhost:8098/buckets/bucket/props

$ curl -v http://localhost:8098/buckets/bucket/props | python -mjson.tool | grep -iE "allow_mult|last_write_wins" 
        "allow_mult": false,
        "last_write_wins": true,
```

Also tried setting `allow_mult=false`/`last_write_wins=true` on the bucket w/o the first props change, but still get the correct results:

```
$ curl -v -X PUT -H "content-type: application/json" -d '{"props": {"allow_mult": false, "last_write_wins": true}}' http://localhost:8098/buckets/bucket2/props

$ curl -v http://localhost:8098/buckets/bucket2/props | python -mjson.tool | grep -iE "allow_mult|last_write_wins" 
        "allow_mult": false,
        "last_write_wins": true,

```

And lastly, tried throwing a reset bucket props in, since the C# example does so, but still the results look good:

```
$ curl -v -X DELETE http://localhost:8098/buckets/bucket3/props

$ curl -v -X PUT -H "content-type: application/json" -d '{"props": {"allow_mult": true, "last_write_wins": false}}' http://localhost:8098/buckets/bucket3/props

$ curl -v -X PUT -H "content-type: application/json" -d '{"props": {"allow_mult": false, "last_write_wins": true}}' http://localhost:8098/buckets/bucket3/props

$ curl -v http://localhost:8098/buckets/bucket3/props | python -mjson.tool | grep -iE "allow_mult|last_write_wins"
        "allow_mult": false,
        "last_write_wins": true,
```

**Closed as completed by jrwest** 2014-04-18 04:37 UTC
Labels: Kanban-Backlog, test, resilience
