### ISSUE TITLE
2i/stats crash

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#631] opened 2013-08-12 19:22 UTC
I'm getting some stats updating errors, as seen [here](https://gist.github.com/reiddraper/4fc4271d2c72edfe7859/raw/7246e1e991e40c3980f6b5c3dd2fa0bac212bc3b/gistfile1.txt) while running some load tests of Riak CS. The only operations running at the time are a bunch of 'cs_bucket_folds'. The frequency of these errors seems to be proportional to the amount of load on the system. As you can see from the timestamps, once they started happening however, they happened frequently.

**Comment by reiddraper** [comment] 2013-08-12 19:29
This too:

```
2013-08-12 15:28:23.680 [warning] <0.338.0>@riak_kv_stat:perform_update:98 exit:{noproc,{gen_server,call,[riak_kv_stat,{get_monitor,index}]}} updating stat {index_create,<0.10899.999>}.
```

**Comment by reiddraper** [comment] 2013-08-12 20:48
cc @evanmcc

**Comment by russelldb** [comment] 2013-08-12 20:56
Some investigation has shown that the issue is timeouts in the call to get monitor for the index / list monitors. The load is about 10 - 20 fsm starts per second, which doesn't seem to harsh.

Disabling the fsm stat (with a patched beam) stops the errors and load seems unaffected.

I guess the right thing to do is figure out why adding a monitor takes so long (can we cast it??)

**Comment by russelldb** [comment] 2013-08-12 21:58
A possible fix https://github.com/basho/riak_kv/pull/632

@reiddraper verified the crashing is fixed, need to check on perf.

**Comment by evanmcc** [comment] 2013-08-14 21:21
#632 was merged, closing.

**Closed as completed by evanmcc** 2013-08-14 21:21 UTC
Labels: Bug, Kanban-Backlog
