### ISSUE TITLE
Leak in memory backend [JIRA: RIAK-1576]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_kv#1064] opened 2014-12-16 20:50 UTC
Mailing list messages:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-December/016416.html
http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-October/016025.html

I have confirmed that you can reproduce this leak using the following bash script to load data into a bucket whose backend is named `mem_backend`:

https://gist.github.com/lukebakken/65cff6499315dc66d7f7

Untested reproducer from the mailing list:

https://gist.github.com/indpnday/76d99c5852e0100c5a04

**Comment by lukebakken** [comment] 2014-12-16 21:37
Note: the `memory` backend has the following configuration (for testing):

```
storage_backend = memory
memory_backend.ttl = 90s
memory_backend.max_memory_per_vnode = 1MB
```

**Comment by lukebakken** [comment] 2015-02-13 16:21
Also see #963

**Comment by lukebakken** [comment] 2015-02-13 17:19
![Image from Git Extensions for the commit](https://s3.amazonaws.com/uploads.hipchat.com/20796/427071/qloKdWV7nVarMt7/riak_kv-issue-963-info.png)

**Comment by HMcKelvey** [comment] 2015-02-27 00:37
Pushing to Jira

**Comment by jcapricebasho** [comment] 2015-04-08 20:04
I've confirmed that the changes in PR #963 are in the 2.0.5 source.

This issue going forward should be treated as a yet to be identified memory leak affecting the 2.x series.

**Comment by Basho-JIRA** [comment] 2015-04-13 20:40
PROD: Attempt to fix in the 2.1.1 release or 2.2 if no 2.1.1 release. 

***[posted via JIRA by Seema Jethani]***

**Comment by engelsanchez** [comment] 2015-06-18 21:12
It seems that we are dealing with the same problem we have with Bitcask TTL. We haven't been able to reproduce this on a one node cluster with n_val of 1, right? AAE is not integrated with backend expiration, and with enough read requests could occasionally resurrect keys that get a fresh new TTL.  Have we tried this with AAE off?

**Comment by engelsanchez** [comment] 2015-06-18 21:20
Err, I mean just plain read-repairs would do it too. You don't even need active anti-entropy.

**Comment by engelsanchez** [comment] 2015-06-18 21:32
My explanation above doesn't really explain the high memory usage part of this. I'll investigate that.

**Comment by seemaj** [comment] 2015-08-20 18:54
@engelsanchez Were you able to investigate this issue?

**Comment by engelsanchez** [comment] 2015-08-20 19:15
This was dealt with in a chat.  The high memory usage came from having AAE enabled, which enables the eleveldb system, which by default allocates enough memory to run with leveldb as a backend.  The workaround until we change eleveldb to stop being so greedy is to configure it to use less: http://docs.basho.com/riak/latest/ops/advanced/backends/leveldb/#Configuring-eLevelDB

As far as I know, there is no actual memory leak in the memory backend.

**Comment by Basho-JIRA** [comment] 2015-11-03 23:07
[~drohrer]Given Engel's comment above, can we investigate this issue and close if needed? 

**_[posted via JIRA by Seema Jethani]**_

**Comment by Basho-JIRA** [comment] 2016-01-22 18:09
We have found at least one legit memory leak in the memory backend thanks to [~nbellerophon]- I'll link the branches from 2.0.6/2.1.3 here and we should get them merged forward from 2.0 to 2.1. 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment] 2016-01-22 18:11
Please use this branch to pull in to 2.0.7. Maybe just PR directly from this to 2.0 branch if it merges cleanly. 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment] 2016-01-22 20:43
PR for 2.0 is at https://github.com/basho/riak_kv/pull/1331 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment] 2016-01-27 22:22
Please review PR linked in the comments. 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment] 2016-02-22 15:54
This is in both 2.0 and develop-2.2 branch. Now done. 

**_[posted via JIRA by Douglas Rohrer]**_

**Closed as completed** 2016-02-22 15:55 UTC
Labels: Bug, JIRA: Closed

**Comment by dieu** [comment] 2016-05-04 20:38
Looks great that this problem is solved, but I still not found any release version with this fixes.

**Comment by lukebakken** [comment] 2016-05-04 20:39
@dieu - based on @JeetKunDoug's comment, it will land in Riak 2.2

**Comment by dieu** [comment] 2016-05-05 22:03
@lukebakken Yes, but how I understand that commit already merged into 2.0 branch (https://github.com/basho/riak_kv/pull/1331) but nobody build new version for 2.x.

**Comment by JeetKunDoug** [comment] 2016-05-05 23:05
@dieu there will be a new 2.0 release in the coming weeks - we've been working hard on some difficult, rather hard-to-fix issues, but 2.0.7 is in the final review/testing phase right now. I can't give you a definitive date "until it's done" but it shouldn't be long now.

**Comment by dieu** [comment] 2016-05-06 00:34
@JeetKunDoug thanks so much for your work! 

Also I have question, what about 2.1.x? it's possible to have this patch into 2.1.x release?

**Comment by JeetKunDoug** [comment] 2016-05-06 12:37
@dieu Riak KV 2.2.0 will be the next release after 2.1.4. Because 2.2.0 will be including an upgrade of Solr to 4.10.4 and an updated Erlang (R16B02_basho10) we felt it was appropriate to bump the minor version of Riak. We do not intend to release any additional Riak versions in the 2.1.x series. I realize this is a bit of a change from Basho's previous versioning schemes (we stayed with 1.4.x for a very long time) we believe it more accurately reflects the changes being made in Riak, and better reflects semantic versioning than what we've done in the past.
