### ISSUE TITLE
Consistent Riak (riak_kv_ensemble_backend) fails to start if AAE is disabled 

### ISSUE THREAD

**Issue by sargun** [basho/riak_kv#959] opened 2014-05-28 15:36 UTC
So, I noticed that if I don't have anti-entropy on, and I enable strongly consistent Riak, it doesn't work. Specifically, what happens is that riak_kv_ensembles sets up the ensembles, but the riak_ensemble_peer never gets past to all_sync state. It appears that this is because the riak_kv_ensemble_backend relies on anti-entropy to perform an exchange before it comes up. See here:

```

sync(Replies, State=#state{ensemble=_Ensemble, id=Id}) ->
    Peers0 = [{Idx, PeerId} || {PeerId={{kv,_PL,_N,Idx},_Node},_Reply}
<- Replies],
    Peers = orddict:from_list(Peers0),
    {{kv, PL, N, Idx}, _} = Id,
    IndexN = {PL,N},
    %% Sort to remove duplicates when changing ownership / forwarded response
    Siblings0 = lists:usort([I || {{{kv,_PL,_N,I},_Node},_Reply} <- Replies]),
    %% Just in case, remove self from list
    Siblings = Siblings0 -- [Idx],

    case local_partition(Idx) of
        true ->
            T0 = erlang:now(),
            Pid = self(),
            spawn_link(fun() ->
                               wait_for_sync(Idx, IndexN, Pid, T0,
Siblings, Peers)
                       end),
            {async, State};
        false ->
            {ok, State}
    end.

wait_for_sync(Idx, IndexN, Pid, T0, Siblings, Peers) ->
    Exchanges = riak_kv_entropy_info:exchanges(Idx, IndexN),
    Recent = [OtherIdx || {OtherIdx, T1, _} <- Exchanges,
                          T1 > T0],
    lager:info("~p/~p: Exchanges: ~p~nT0: ~p~nRecent: ~p~nSibs: ~p",
                [Idx, IndexN, Exchanges, T0, Recent, Siblings]),
    Need = length(Siblings),
    Finished = length(Recent),
    Local = local_partition(Idx),
    Complete = ((Siblings -- Recent) =:= []),
    if not Local ->
            lager:info("Partition ownership changed. No need to sync."),
            riak_ensemble_backend:sync_complete(Pid, []);
       Complete ->
            lager:info("Complete ~b/~b :: ~p -> ~p~n", [Finished,
Need, Idx, Pid]),
            SyncPeers = [orddict:fetch(PeerIdx, Peers) || PeerIdx <- Siblings],
            riak_ensemble_backend:sync_complete(Pid, SyncPeers);
       true ->
            lager:info("Not yet ~b/~b :: ~p", [Finished, Need, Idx]),
            timer:sleep(10000),
            wait_for_sync(Idx, IndexN, Pid, T0, Siblings, Peers)
    end.
```

(I uncommented the debugging). If riak_kv_entropy_manager is not enabled, then riak_kv_entropy_info:exchanges will always be empty. Can we either (1) manually trigger AAE exchange upon noticing that strong consistency is enabled (I imagine you can do this by setting the mode to manual, and then queueing up the AAE jobs), (2) throw a warning to the user saying that they should enable AAE.

**Comment by jburwell** [comment] 2014-06-02 20:28
Working up a test case to reproduce.

**Comment by sargun** [comment] 2014-06-02 20:31
Turn off aae, and try to start riak_kv, with strong consistency on. Then look at riak ensembles, and they will never reach quorum.

**Comment by jburwell** [comment] 2014-06-04 18:04
@sargun you are correct -- this behavior is as designed.  When AAE is disabled and strong consistency is enabled, strongly consistent operations will not work because ensembles will never gain quorum.  However, non-consistent operations will continue to work.  We plan to add a log, as well as, riak admin warning regarding the inconsistent configuration.

cc @jtuple

**Comment by sargun** [comment] 2014-06-04 19:30
Why not do the aae sync the first time when the riak_ensemble starts up? Riak_kv_entropy_manager supports being executed manually. You don't need continual synchronization, just during the ensemble member start-up.

**Comment by jburwell** [comment] 2014-06-10 20:07
@sargun AAE tree construction is an long running operation (often measured in hours to days depending on dataset size). Thus, Riak doesn't build an AAE tree on-demand for a given exchange. Riak builds AAE trees once a week, and keeps them up-to-date in realtime as K/V operations come in. If AAE is disabled, these trees aren't being maintained in realtime and thus all necessary trees would need to be built from scratch. Since that could take days, and therefore leave ensembles unavailable for days, this is operationally unfeasible.

/cc @jtuple

**Comment by jburwell** [comment] 2014-06-10 20:14
Open the following PRs to verify proper Riak startup under the conditions described, log a warning on startup, and check the strong consistency/AAE configuration using Riaknostic:
- riak_test: https://github.com/basho/riak_test/pull/636
- riak_kv: https://github.com/basho/riak_kv/pull/978
- riaknostic: https://github.com/basho/riaknostic/pull/83

/cc @kellymclaughlin @jtuple @bsparrow435

**Comment by jburwell** [comment] 2014-06-16 13:32
All PRs have been approved and merged.

**Closed as completed by jburwell** 2014-06-16 13:32 UTC
Labels: Bug
