### ISSUE TITLE
Like ring_members in /stats but with PB and HTTP

### ISSUE THREAD

**Issue by simonvc** [basho/riak_kv#461] opened 2013-01-03 14:00 UTC
It would be really useful for us automation and monitoring types to be able to connect to any running node of a riak cluster and get the /stats page, then extract out a list of all the nodes in the cluster, with their bound ip and port.

e.g. we currently have in /stats

ring_members: [
"riak1@127.0.0.1",
"riak2@127.0.0.1",
"riak3@127.0.0.1",
"riak4@127.0.0.1",
"riak5@127.0.0.1"
],

I'd really like to see:

ring_members_http: [
"127.0.0.1:11098",
"127.0.0.1:12098",
"127.0.0.1:13098",
"127.0.0.1:14098",
"127.0.0.1:15098"
],

and

ring_members_pb: [
"10.0.2.11:11099",
"10.0.2.12:12099",
"10.0.2.13:13099",
"10.0.2.14:14099",
"10.0.2.15:15099",],

**Comment by evanmcc** [comment] 2013-08-09 21:54
seems reasonable but not on the near term roadmap, marked as a feature request.

**Closed as completed by evanmcc** 2013-08-09 21:54 UTC

**Comment by seancribbs** [comment] 2013-08-09 21:58
Dupe of basho/riak#356 actually

**Comment by evanmcc** [comment] 2013-08-09 22:17
thanks, untagged
