### ISSUE TITLE
riak_kv_stat:re_register_stat/1 has case_clause exception

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_kv#537] opened 2013-04-26 16:31 UTC
Today's 'master' branch has `case_clause` exceptions being thrown ... example errors from MvM:

```
2013-04-26 12:09:27.979 [error] emulator Error in process <0.29138.49> on node 'riak@127.0.0.1' with exit value: {{case_clause,{add_pid,<0.29109.49>}},[{riak_kv_stat,re_register_stat,1,[{file,"src/riak_kv_stat.erl"},{line,485}]},{riak_kv_stat,stat_repair_loop,0,[{file,"src/riak_kv_stat.erl"},{line,478}]}]}
```

My first guess is that the clauses of `do_update/1` that have `add_monitor(MumbleSomething, Pid)` are the cause: `add_monitor` is not returning `ok`.

**Comment by russelldb** [comment] 2013-04-26 16:51
Can I get some more? There will be a warning like `ErrorClass:Error updating stat StatName` in the logs. Looks like a merge error, maybe, can't see any clause of `do_update` that handles an argument `{add_pid, pid()}`

**Comment by slfritchie** [comment] 2013-04-26 17:10
This is all that I have from @matthewvon, he's the generator & owner of the logs.

```
2013-04-26 12:09:27.973 [error] <0.29006.49> gen_server riak_kv_stat terminated with reason: no match of right hand value [] in riak_kv_stat:handle_call/3 line 126
2013-04-26 12:09:27.973 [error] <0.29006.49> CRASH REPORT Process riak_kv_stat with 2 neighbours exited with reason: no match of right hand value [] in riak_kv_stat:handle_call/3 line 126 in gen_server:terminate/6 line 747
2013-04-26 12:09:27.973 [error] <0.28981.49> Supervisor riak_core_stats_sup had child riak_kv_stat started with riak_kv_stat:start_link() at <0.29006.49> exit with reason no match of right hand value [] in riak_kv_stat:handle_call/3 line 126 in context child_terminated
2013-04-26 12:09:27.979 [error] emulator Error in process <0.29138.49> on node 'riak@127.0.0.1' with exit value: {{case_clause,{add_pid,<0.29109.49>}},[{riak_kv_stat,re_register_stat,1,[{file,"src/riak_kv_stat.erl"},{line,485}]},{riak_kv_stat,stat_repair_loop,0,[{file,"src/riak_kv_stat.erl"},{line,478}]}]}
```

**Comment by russelldb** [comment] 2013-04-26 17:11
Ah! Got it, thank you.

The problem is here - https://github.com/basho/riak_kv/blob/master/src/riak_kv_stat.erl#L542

There is no configured way to re-register that kind of stat.

Will patch ASAP. Thanks.

I think I can see how the bug came into being too, that stat (the monitors for fsms) was in master, the repair stuff in 1.3, when merged - boom.

**Comment by russelldb** [comment] 2013-06-13 16:56
https://github.com/basho/riak_kv/pull/577 Fixes.

**Closed as completed** 2013-07-02 18:53 UTC
Labels: Kanban-Done, Kanban-Cabal-Core
