### ISSUE TITLE
get/put FSM supervisor PID leak when overload protection is enabled [JIRA: RIAK-2157]

### ISSUE THREAD

**Issue by ian-mi** [basho/riak_kv#1178] opened 2015-09-02 19:16 UTC
Calls to `riak_kv_get_fsm_sup:start_get_fsm` leave abandoned PIDs in the `riak_kv_get_fsm_sup` state because FSMs are linked to a sidejob supervisor rather than the get FSM supervisor. A similar issue applies to the put FSM supervisor. This can cause extended shutdown times as the supervisor attempts to iterate through millions of dead PIDs.

**Comment by jonmeredith** [comment] 2015-09-02 21:32
Do you have a reproducer or customer ticket this came from?

**Comment by ian-mi** [comment] 2015-09-04 15:59
I've reproduced the issue by doing the following from riak attach on a new node:

supervisor:count_children(riak_kv_get_fsm_sup).
[{specs,1},{active,0},{supervisors,0},{workers,0}]

riak_kv_get_fsm_sup:start_get_fsm(node(), [<<"">>, <<"bucket">>, <<"key">>, []]).
{ok,<0.5520.0>}

process_info(list_to_pid("<0.5520.0>")).
undefined

supervisor:count_children(riak_kv_get_fsm_sup).  
[{specs,1},{active,0},{supervisors,0},{workers,1}]

**Comment by jonmeredith** [comment] 2015-10-01 20:29
The riak_kv_get_fsm_sup should be deprecated. The only consumer I could find is `riak_repl_util:reap/3` called in `riak_repl_util:do_repl_put/3` which could be modified to just call start_link instead.

If using sidejob it would obey overload protection which is a good thing and not create a link to the calling process.  The case where overload protection is disabled is more tricky - if the FSM crashes it would be linked to the caller.  `reap/3` could call unlink, but there is a race.

We should check with cliserv if there has been a case where we have disabled sidejob.  It was a 'get-out-of-jail' option while the code proved itself in production, so we could clean all of that stuff up to just require sidejob.

/cc: @JeetKunDoug

**Comment by ian-mi** [comment] 2015-10-06 00:18
It seems incorrect that riak_kv_get_fsm:start_link does not link to the caller when sidejob is enabled as that breaks the expected semantics of start_link. One fix I've been thinking of is to manually call link when sidejob is used. However, the reason start_link has been used seems to be just an artifact of avoiding the get_fsm_sup for performance reasons. Based on my discussions with others in cliserv, we have not seen anyone disabling the FSM limit, so I agree that the cleanest solution would be to always use sidejob and perhaps rename the start function to reflect that it does not link to its caller.

**Comment by jonmeredith** [comment] 2015-10-06 23:48
Probably go with the rename. You could set up a monitor instead. That
should return exit on an already dead pid.

**Comment by Basho-JIRA** [comment] 2016-04-22 17:02
[~hmckelvey][~pbrewer] This has been seen affecting a customer more severely than we may have originally thought. We should schedule it for fix ASAP. 

***[posted via JIRA by Douglas Rohrer]***

**Comment by nerophon** [comment] 2016-04-27 13:38
This is severely affecting a customer. It prevents them from restarting cleanly, which indirectly resulted in a costly outage.

**Comment by nickelization** [comment] 2016-05-09 17:12
PR'd a small, safe fix for this in the 2.0.x branch here: https://github.com/basho/riak_repl/pull/742

Leaving this issue open though, since I will write a better fix for the 2.2 branch involving riak_kv APIs and removing the overload-disabled code path.

**Comment by Basho-JIRA** [comment] 2016-05-18 17:32
Removing 2.2 tag: will open a separate issue for the 2.2 version of the bug fix, since it's substantially different and still in progress. 

**_[posted via JIRA by Nick Marino]**_

**Comment by nickelization** [comment] 2016-05-18 17:33
Stupid JIRA. Reopening...

**Comment by Basho-JIRA** [comment] 2016-05-18 17:53
Ignore the above comment. It was posted involuntarily due to my commenting on the deletion of a redundant GitHub issue that JIRA also created without asking me. 

***[posted via JIRA by Nick Marino]***

**Comment by Basho-JIRA** [comment] 2016-05-19 05:55
[~drohrer]this is the 207 pid leak story.  Doesn't have a fix version yet, so just wanted to double check with you that you see it is merged.  I probably shouldn't just plug in fix versions.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment] 2016-05-19 13:47
[~pbrewer] here is the PR where this was merged into the 2.0 branch: https://github.com/basho/riak_repl/pull/742

Does this mean I should put "2.0.7" into the "fix version" field? I've never really payed attention to that field before, so want to make sure I understand it before I go messing with it. 

**_[posted via JIRA by Nick Marino]**_

**Comment by Basho-JIRA** [comment] 2016-05-19 15:04
If it's fixed and merged, yes, please mark it as "2.0.7" in the fix version.

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment] 2016-06-20 18:11
For 2.0.7, the fix is in https://github.com/basho/riak_repl/pull/742

For 2.2.0, a more complete fix is in https://github.com/basho/riak_kv/pull/1420 (removing the old code completely). 

**_[posted via JIRA by Douglas Rohrer]**_

**Closed as completed** 2016-08-01 17:12 UTC
Labels: JIRA: Closed
