### ISSUE TITLE
riak-2.1.4-1 on ubuntu crashes on startup [JIRA: RIAK-2501]

### ISSUE THREAD

**Issue by kappac** [basho/riak_kv#1394] opened 2016-04-15 12:25 UTC
I made a clean install of riak-2.1.4-1 package on Ubuntu 14.04 server from PackageCloud.

With default config server starts well as expected.

After nodename changing to riak@system_ip server crashes during start up:

`{"Kernel pid terminated",application_controller,"{application_start_failure,riak_core,{bad_return,{{riak_core_app,start,[normal,[]]},{'EXIT',{{function_clause,[{orddict,fetch,['riak@10.200.200.185',[{'riak@127.0.0.1',[{{riak_control,member_info_version},[v1,v0]},{{riak_core,bucket_types},[true,false]},{{riak_core,fold_req_version},[v2,v1]},{{riak_core,net_ticktime},[true,false]},{{riak_core,resizable_ring},[true,false]},{{riak_core,security},[true,false]},{{riak_core,staged_joins},[true,false]},{{riak_core,vnode_routing},[proxy,legacy]},{{riak_kv,anti_entropy},[enabled_v1,disabled]},{{riak_kv,crdt},[[pncounter,riak_dt_pncounter,riak_dt_orswot,riak_dt_map],[pncounter],[]]},{{riak_kv,crdt_epoch_versions},[[{riak_dt_map,2},{riak_dt_orswot,2},{riak_dt_pncounter,2}],[{riak_dt_pncounter,2}]]},{{riak_kv,handoff_data_encoding},[encode_raw,encode_zlib]},{{riak_kv,index_backpressure},[true,false]},{{riak_kv,legacy_keylisting},[false]},{{riak_kv,listkeys_backpressure},[true,false]},{{riak_kv,mapred_2i_pipe},[true,false]},{{riak_kv,mapred_system},[pipe]},{{riak_kv,object_format},[v1,v0]},{{riak_kv,put_fsm_ack_execute},[enabled,disabled]},{{riak_kv,secondary_index_version},[v3,v2,v1]},{{riak_kv,vclock_data_encoding},[encode_zlib,encode_raw]},{{riak_kv,vnode_vclocks},[true,false]},{{riak_pipe,trace_format},[ordsets,sets]}]}]],[{file,\"orddict.erl\"},{line,72}]},{riak_core_capability,renegotiate_capabilities,1,[{file,\"src/riak_core_capability.erl\"},{line,441}]},{riak_core_capability,handle_call,3,[{file,\"src/riak_core_capability.erl\"},{line,213}]},{gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,239}]}]},{gen_server,call,[riak_core_capability,{register,{riak_core,vnode_routing},{capability,[proxy,legacy],legacy,{riak_core,legacy_vnode_routing,[{true,legacy},{false,proxy}]}}},infinity]}}}}}}"}`

**Comment by JeetKunDoug** [comment] 2016-04-15 18:09
Thank you for reporting this. I assume you're running Ubuntu 12.04? If so, please see #1393 and, if could, close this issue if it is the same problem. We will be issuing updated packages soon (today hopefully) that fix a permissions issue in the packaging. No code changes, just a packaging change, so it will be released as riak-2.1.4-2.

**Comment by kappac** [comment] 2016-04-16 10:49
Hi, thank you for your response! I'm using Ubuntu 14.04.4 LTS Server version. I tried suggestions in https://github.com/basho/riak_kv/issues/1393. I got this problem after permissions change.

**Comment by kappac** [comment] 2016-04-16 11:18
I got the same problem with 2.1.4-2 build, but figured out the way to fix.

Steps to reproduce:
1. Run riak first time           ->            system starts, and everything works ok.
2. Stop riak.
3. Change config file(nodename or listener.http.internal).
4. Start riak                          ->            system craches with error mensioned above.

The same happens if I try restart riak with `service riak restart` instead of stopping and starting.

Fix: `rm -rf /var/lib/riak/ring/*`

**Comment by JeetKunDoug** [comment] 2016-04-19 17:26
Sorry for misreading your stack trace - I should have realized it's a different issue. You are correct in that if you start a Riak node without setting the node name, and then stop the node/fix the name and restart, you will end up with this issue. We are working to make the cause of this particular crash more obvious than it is.

I'm going to close this now - please let us know if there's anything else you need.

**Closed as completed by JeetKunDoug** 2016-04-19 17:26 UTC
Labels: JIRA: Closed

**Comment by kappac** [comment] 2016-04-20 15:03
Thank you for your response! Nothing else.
