### ISSUE TITLE
memory backend max_memory & ttl settings don't play nice together

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_kv#717] opened 2013-11-01 19:07 UTC
https://github.com/basho/riak_kv/tree/pevm-membackend-1.1backport contains a few fixes that need to be applied to develop.

In addition, need to make sure that we're trying to trim the timeref table (where it exists) when something expires on get.

**Comment by engelsanchez** [comment] 2013-11-01 19:08
And in addition I believe we don't delete entries from the time table when doing a put over an existing object.

**Comment by reiddraper** [comment] 2014-05-12 16:27
I'm moving this to 2.1. Please speak up @engelsanchez @evanmcc, if this is an issue.

**Comment by evanmcc** [comment] 2014-05-12 16:30
I have a patch against this already, we should shoehorn it into the RC if
at all possible.  Just need to test it and forward-port from 1.4.

**Comment by reiddraper** [comment] 2014-05-12 17:31
@evanmcc can you go ahead and make a PR for the backport?

**Comment by reiddraper** [comment] 2014-05-12 17:31
Moving back to RC milestone.

**Comment by reiddraper** [comment] 2014-05-19 16:17
Can this be closed now in favor of #940?

**Comment by kellymclaughlin** [comment] 2014-05-29 19:59
seems to be a duplicate of #940. close ping.

**Comment by evanmcc** [comment] 2014-05-29 20:20
The 2.0 version isn't entirely straightforward.  I am working on getting a PR and an integration test together.  I'll close this one when the PRs open.  That should be today or tomorrow, but we've never really had any tests for the memory backend, so it's taking a bit.

**Comment by evanmcc** [comment] 2014-05-30 21:34
Sorry, this is taking me much longer than I anticipated.  It covers quite a lot of ground, because the memory backend has to be tested in a number of configurations, then retested under the multi backend.  That is mostly working, but I am experiencing some non-deterministic failures due to the occasional long leave and a stubborn weird miscalculation of something that should be static.  The last one is the most worrying, as I can't tell if it's a bug in the test or the backend.  Anyway, hopefully I'll be done with this soon.

**Comment by kellymclaughlin** [comment] 2014-06-03 22:56
Looks like we're merged up, closing this out.

**Closed as completed by kellymclaughlin** 2014-06-03 22:56 UTC
Labels: Kanban-Backlog
